config/routes.rb
Rails.application.routes.draw do
# Devise
  devise_for :users

# Custom Root
  root to: 'boards#index'

# Custom Routes
  # get 'boards/:board_id', to: 'notecards#index', except: [:new]
  get 'notecards', to: 'notecards#all'

# Nexted Resources
  resources :boards, except: [:show] do
    resources :notecards
  end
  
  resources :notecards, except: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :comments
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :notecards
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :notecard
end

app/models/notecard.rb
class Notecard < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # models look good for the most part. Would love to see some validations, but associations look solid based on schema.

  # i told you this was hacky! I encourage you try adding custom attributes to the devise user model. Check out the devise docs for more info on how to do that.
  def username
    self.email.split('@')[0].capitalize
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notecards
  has_many :comments
  has_many :boards, through: :notecards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # :+1:
  before_action :set_board, except: [:index, :new, :create]

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    if @board = Board.create!(board_params)
      flash[:notice] = "#{@board.title} was successfully created!"
      redirect_to board_notecards_path(@board)
    else
      flash[:alert] = "#{@board.title} was not created."
      render :new
    end
  end


  def edit
  end

  def update
    if @board.update!(board_params)
      flash[:notice] = "#{@board.title} was successfully updated!"
      redirect_to board_notecards_path(@board)
    else
      flash[:alert] = "#{@board.title} was not updated."
      render :edit
    end
  end

  def destroy
    if @board.destroy
      flash[:notice] = "#{@board.title} was removed."
      redirect_to boards_path
    else
      flash[:alert] = "#{@board.title} was not removed."
      redirect_to board_notecards_path(@board)
    end
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :status)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_notecard, only: [:create, :destroy]

  def create
    @comment = @notecard.comments.create!(comment_params.merge(user:current_user))
    redirect_to board_notecard_path(@notecard)
  end

  def destroy
    @comment = current_user.comment.find(params[:id])
    @comment.destroy
    redirecto_to board_notecard_path(@notecard)
  end

private
  def set_notecard
    @notecard = Notecard.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/notecards_controller.rb
class NotecardsController < ApplicationController
  before_action :set_board, except: [:all, :destroy]
# :+1:
  def all
    @notecards = Notecard.all
  end

  def index
    @notecards = @board.notecards.all
  end

  def show
    @notecard = @board.notecards.find(params[:id])
  end

  def new
    @notecard = Notecard.new
  end

  def create
    if @notecard = @board.notecards.create!(notecard_params.merge(user:current_user))
      flash[:notice] = "#{@notecard.task} was successfully created!"
      redirect_to board_notecards_path(@board)
    else
      flash[:alert] = "#{@notecard.task} was not created."
      render :new
    end
  end

  def edit
    @notecard = Notecard.find(params[:id])
  end

  def update
    @notecard = Notecard.find(params[:id])
    if @notecard.update(notecard_params)
      flash[:notice] = "#{@notecard.task} was successfully updated!"
      redirect_to board_notecards_path
    else
      flash[:alert] = "#{@notecard.task} was not updated."
      render :edit
    end
  end

  def destroy
    @notecard = current_user.notecards.find(params[:id])
    if @notecard.destroy
      flash[:notice] = "#{@notecard.task} was removed."
      redirect_to board_notecards_path
    else
      flash[:alert] = "#{@notecard.task} was not removed."
      redirect_to board_notecards_path
    end
  end

  private
  def set_board
    @board = Board.find(params[:board_id])
  end

  def notecard_params
    params.require(:notecard).permit(:task, :date, :status, :accomplished, :to_do, :roadblock, :user_id, :board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notecards_helper.rb
module NotecardsHelper
end

app/views/boards/_form.html.erb
<div class="col-md-3"></div>

<div class="form col-md-6">
  <div class="well well-lg">
    <%= form_for [@board], :html => {:class => "form-group center"} do |f| %>

    <!-- Board Title -->
    <div class="form-group">
      <%= f.label :title, "Board Title:", class: "col-md-12 control-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <!-- Board Status -->
    <div class="form-group">
      <%= f.label :status, "Board Status:", class: "col-md-12 control-label" %>
      <%= f.select(:status, options_for_select(["Not Started", "In Progress", "Complete"]), {class: "form-control"})  %>
    </div>

    <!-- Submit -->
    <div class="form-submit">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

<div class="col-md-3"></div>

app/views/boards/edit.html.erb
<div class="page_title">
  <h1>Edit Board</h1>
</div>

<%= render "form" %>

<div class="col-md-12">
  <%= link_to "Back To Board", board_notecards_path(@board), class: "btn btn-info btn-lg" %>
  <%= link_to "Delete This Board", @board, class: "btn btn-warning btn-lg",  method: :delete, data: { confirm: "Are you sure?"} %>
</div>

app/views/boards/index.html.erb
<!-- Current User : Available Actions -->
<% if current_user %>
<!-- View All Boards + Add New Board -->
<div class="page_title">
  <h1>All Boards <%= link_to new_board_path, class: "btn btn-success" do  %>
    <i class="glyphicon glyphicon-plus"></i>
    <% end %></h1>
  </div>
  <!-- Not Current User : View Boards -->
  <% else %>
  <!-- View All Boards -->
  <div class="page_title"><h1>All Boards</h1></div>
  <% end %>

  <% @boards.each do |board| %>
  <div class="well well-lg">
    <ul>
      <li class="board_title"><%= link_to board.title, board_notecards_path(board) %></li>
      <li class="board_status"><%= board.status %></li>
    </ul>
  </div>
  <% end %>

app/views/boards/new.html.erb
<div class="page_title">
  <h1>Create New Board</h1>
</div>

<%= render "form" %>

<div class="col-md-12">
  <%= link_to "Back To All Boards", boards_path, class: "btn btn-info btn-lg" %>
</div>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<h2><%= @board.status %></h2>
<%= link_to "All Boards", boards_path %>

<!-- Show Notecards For This Board -->
<% @board.notecards.each do |notecard| %>
<ul>
  <li>
    <p>Task:</p>
    <p><%= link_to notecard.task, board_notecards_path(notecard) %></p>
  </li>
  <li>
    <p>Date:
    <p><%= notecard.date %></p>
  </li>
  <li>
    <p>Task Status:</p>
    <p><%= notecard.status %></p>
  </li>
  <li>
    <p>What did you accomplish yesterday?</p>
    <p><%= notecard.accomplished %></p>
  </li>
  <li>
    <p>What are you doing today?</p>
    <p><%= notecard.to_do %></p>
  </li>
  <li>
    <p>What are the roadblocks (if any)?</p>
    <p><%= notecard.roadblock %></p>
  </li>
</ul>
<!-- Notecard Owner Can Edit Or Delete Card -->
  <% if current_user && notecard.user == current_user %>
    <%= link_to 'Edit Notecard', edit_board_notecard_path(@board, notecard) %>
    <%= link_to 'Delete', [@board, notecard], method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

<!-- Any Current User Can Edit or Delete the Board if Logged In -->
<% if current_user %>
  <%= link_to 'Edit Board', edit_board_path(@board) %>
  <%= link_to 'Delete', @board, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@notecard, @notecard.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- all the views looks amazing jen! -->
<html>
<head>
  <title>Daily Scrum Board</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
      <%= link_to "Daily Scrum", root_path, class: "navbar-brand" %>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to "View All Boards", root_path %></li>
        <li><%= link_to "View All Notecards", notecards_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <!-- Main Content -->
  <div id="main-container" class="container">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
        <% end -%>
      </div>
    </div>
    <div id="content" class="col-md-12">
      <%= yield %>
    </div>
  </div>

  <footer></footer>

</body>
</html>

app/views/layouts/home.html.erb
<!-- If not current user -->
  <!-- Login -->
  <!-- Sign up -->
  <!-- View all notecards -->

<!-- <% else %> -->

  <!-- Logout -->
  <!-- View my notecards -->
  <!-- View all notecards -->

app/views/notecards/_form.html.erb
<div class="col-md-2"></div>

<div class="form col-md-8">
  <div class="form">
    <div class="well well-lg">
      <%= form_for [@board, @notecard], :html => {:class => "form-group center"} do |f| %>

      <!-- Task -->
      <div class="form-group">
        <%= f.label :task, "Task:", class: "col-md-12 control-label" %>
        <%= f.text_field :task, class: "form-control" %>
      </div>

      <!-- Notecard dates -->
      <div class="form-group">
        <%= f.label :date, "Date (Enter as YYYY-MM-DD):", class: "col-md-12 control-label" %>
        <%= f.text_field :date, class: "form-control"  %>
      </div>

      <!-- Task Status -->
      <div class="form-group">
        <%= f.label :status, "Task Status", class: "col-md-12 control-label" %>
        <%= f.select(:status, options_for_select(["Not Started", "In Progress", "Complete"]), {class: "form-control"}) %>
      </div>

      <!-- What did you accomplish yesterday? -->
      <div class="form-group">
        <%= f.label :accomplished, "What did you accomplish yesterday?", class: "col-md-12 control-label" %>
        <%= f.text_area :accomplished, class: "form-control" %>
      </div>

      <!-- What are you doing today? -->
      <div class="form-group">
        <%= f.label :to_do, "What are you doing today?", class: "col-md-12 control-label" %>
        <%= f.text_area :to_do, class: "form-control" %>
      </div>

      <!-- What are the roadblocks? -->
      <div class="form-group">
        <%= f.label :roadblock, "What are the roadblocks?", class: "col-md-12 control-label" %>
        <%= f.text_area :roadblock, class: "form-control" %>
      </div>

      <!-- Submit -->
      <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>

</div>

<div class="col-md-2"></div>

app/views/notecards/all.html.erb
<div class="page_title">
  <h1>All Notecards</h1>
</div>

<!-- Show all notecards -->
<% @notecards.each do |notecard| %>
<div class="notecard col-md-6">
  <div class="well well-lg">
    <ul>
      <!-- Notecard Title -->
      <li class="notecard_title"><%= link_to notecard.task, board_notecard_path(notecard.board_id, notecard) %></li>

      <!-- Notecard Date -->
      <li><p class="notecard_column">Date: <%= notecard.date %></p></li>

      <!-- Notecard Status -->
      <li><p class="notecard_column">Task Status: <%= notecard.status  %></p></li>

      <!-- Notecard Accomplish? -->
      <li>
        <p class="notecard_column"><i>What did you accomplish yesterday?</i></br><%= notecard.accomplished  %></p>
      </li>

      <!-- Notecard To Do? -->
      <li>
        <p class="notecard_column"><i>What are you doing today?</i></br><%= notecard.to_do  %></p>
      </li>

      <!-- Notecard Roadblocks? -->
      <li>
        <p class="notecard_column"><i>What are the roadblocks (if any)?</i></br><%= notecard.roadblock  %></p>
      </li>
    </ul>

    <!-- Notecard Edit -->
    <% if current_user && notecard.user == current_user %>
    <%= link_to "Edit Notecard", edit_board_notecard_path(notecard.board_id, notecard), class: "btn btn-info btn-lg"  %>
    <% end %>
  </div>
</div>
<% end %>

app/views/notecards/edit.html.erb
<div class="page_title">
  <h1>Edit Notecard</h1>
</div>

<div class="col-md-12">
  <%= render "form" %>
</div>

<div class="actions col-md-12">
  <%= link_to "Back To Board", board_notecard_path(@board, @notecard), class: "btn btn-info btn-lg" %>
  <%= link_to "Delete Notecard", [@board, @notecard], class: "btn btn-warning btn-lg", method: :delete, data: { confirm: "Are you sure?"} %>
</div>

app/views/notecards/index.html.erb
<div class="page_title">
  <h1><%= @board.title %></h1>
  <h3>Status: <%= @board.status %></h3>
</div>

<div class="new_card_button">
  <% if current_user %>
    <%= link_to new_board_notecard_path(@board, @notecard), class: "btn btn-success" do  %>
      <i class="glyphicon glyphicon-plus"> Add Notecard</i>
    <% end %>
  <% end %>
</div>

<!-- Show Notecards For This Board -->
<% @board.notecards.each do |notecard| %>
<div class="notecard col-md-6">
  <div class="well well-lg">
    <ul>
      <!-- Notecard Title -->
      <li class="notecard_title"><%= link_to notecard.task, board_notecard_path(@board, notecard) %></li>

      <!-- Notecard Date -->
      <li><p class="notecard_column">Date: <%= notecard.date %></p></li>

      <!-- Notecard Status -->
      <li><p class="notecard_column">Task Status: <%= notecard.status  %></p></li>

      <!-- Notecard Accomplish? -->
      <li>
        <p class="notecard_column"><i>What did you accomplish yesterday?</i></br><%= notecard.accomplished  %></p>
      </li>

      <!-- Notecard To Do? -->
      <li>
        <p class="notecard_column"><i>What are you doing today?</i></br><%= notecard.to_do  %></p>
      </li>

      <!-- Notecard Roadblocks? -->
      <li>
        <p class="notecard_column"><i>What are the roadblocks (if any)?</i></br><%= notecard.roadblock  %></p>
      </li>
    </ul>

    <!-- Notecard Owner Can Edit Or Delete Card -->
    <% if current_user && notecard.user == current_user %>
    <%= link_to "Edit Notecard", edit_board_notecard_path(notecard.board_id, notecard), class: "btn btn-info btn-lg" %>
    <%= link_to "Delete Notecard", [@board, notecard], class: "btn btn-warning btn-lg", method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>
</div>
<% end %>

<!-- Any Current User Can Edit or Delete the Board if Logged In -->
<div class="board_actions col-md-12">
  <% if current_user %>
  <%= link_to "Edit Board", edit_board_path(@board), class: "btn btn-info btn-lg" %>
  <%= link_to "Delete Board", @board, class: "btn btn-warning btn-lg", method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</div>

app/views/notecards/new.html.erb
<div class="page_title">
  <h1>New Notecard</h1>
</div>

<%= render "form" %>

<div class="col-md-12">
  <%= link_to "Back To Notecards", board_notecards_path(@board), class: "btn btn-info btn-lg" %>
</div>

app/views/notecards/show.html.erb
<div class="page_title">
  <h1><%= @board.title %></h1>
  <h3>Status: <%= @board.status %></h3>
</div>

<div class="actions col-md-12">
  <%= link_to "Back to Board", board_notecards_path, class: "btn btn-info btn-lg"  %>
</div>

<div class="col-md-3">
</div>

<div id="single_card" class="notecard col-md-6">
  <div class="well well-lg">
    <ul>
      <!-- Notecard Title -->
      <li class="notecard_title"><%= link_to @notecard.task, board_notecard_path(@board, @notecard) %></li>

      <!-- Notecard Date -->
      <li><p class="notecard_column">Date: <%= @notecard.date %></p></li>

      <!-- Notecard Status -->
      <li><p class="notecard_column">Task Status: <%= @notecard.status  %></p></li>

      <!-- Notecard Accomplish? -->
      <li>
        <p class="notecard_column"><i>What did you accomplish yesterday?</i></br><%= @notecard.accomplished  %></p>
      </li>

      <!-- Notecard To Do? -->
      <li>
        <p class="notecard_column"><i>What are you doing today?</i></br><%= @notecard.to_do  %></p>
      </li>

      <!-- Notecard Roadblocks? -->
      <li>
        <p class="notecard_column"><i>What are the roadblocks (if any)?</i></br><%= @notecard.roadblock  %></p>
      </li>
    </ul>
  </div>
</div>

<!-- Add a comment -->
<h2>Add a comment</h2>
<%= render "comments/form" %>



<div class="col-md-3">
</div>

<div class="actions col-md-12">
  <% if current_user && @notecard.user == current_user %>
  <%= link_to "Edit Notecard", edit_board_notecard_path(@board, @notecard), class: "btn btn-info btn-lg" %>
  <%= link_to "Delete Notecard", [@board, @notecard], class: "btn btn-warning btn-lg", method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</div>